### ISSUE TITLE
filterLocal: true gets ignored

### ISSUE THREAD

**Issue by aheissenberger** [arabold/serverless-sentry-plugin#17]
What is wrong with my code that the configuration for "filterLocal" gets ignored?
Or how can I access the right instance of the wrapper in my App Object?

This is my excerpt from `serverless.yml`:
```
  sentry:
    dsn: https://XXX@sentry.io/YYYYY
    organization: ORG
    project: PRJ
    authToken: *****
    release: true
    filterLocal: true
```

starting `server less offline`:
```
...
Serverless: GET /getYYYY/b/a (λ: getYYYY)
Serverless: The first request might take a few extra seconds
Sentry **disabled in local environment**
...
```

this is the code in the `handler.js`:
```
import 'source-map-support/register';
import Raven from 'raven';
import RavenLambdaWrapper from 'serverless-sentry-lib';

import AppHandler from './app';

const handler = new AppHandler({});
export const getYYYY = RavenLambdaWrapper.handler(Raven, handler.getwlanuser() );
```

this is the code in the app.js:
```
import Raven from 'raven';

export default class {

  getYYYY() {
    return (event, context, cb) => { 
       Raven.captureMessage('Test Start');
    }
  }
}
```
