### ISSUE TITLE
Cannot load config from an external file

### ISSUE THREAD

**Issue by BlitzBanana** [arabold/serverless-sentry-plugin#26]
Hello

I'm facing a problem using external .yml config files in my serverless.yml.

This works:

```yml
# serverless.yml
custom:
  sentry:	
    dsn: https://xxxx:yyyy@sentry.io/zzzz
    organization: my-organziation
    project: my-project
    authToken: my-token
    release: true
```

This doesn't work:

```yml
# serverless.yml

custom: ${file(staging.yml)}
```

```yml
# staging.yml
sentry:	
  dsn: https://xxxx:yyyy@sentry.io/zzzz
  organization: my-organziation
  project: my-project
  authToken: my-token
  release: true
```

This doesn't work either:

```yml
# serverless.yml

custom:
  env: ${file(staging.yml)}
  sentry: ${self:custom.env.sentry}
```

```yml
# staging.yml
sentry:	
  dsn: https://xxxx:yyyy@sentry.io/zzzz
  organization: my-organziation
  project: my-project
  authToken: my-token
  release: true
```

The only solution is:

```yml
# serverless.yml

custom:
  env: ${file(staging.yml)}
  sentry:	
    dsn: ${self:custom.env.sentry.dsn}	
    environment: ${self:custom.env.sentry.environment}
    organization: ${self:custom.env.sentry.organization}
    project: ${self:custom.env.sentry.project}
    authToken: ${self:custom.env.sentry.authToken}
    release: ${self:custom.env.sentry.release}
```

```yml
# staging.yml
sentry:	
  dsn: https://xxxx:yyyy@sentry.io/zzzz
  organization: my-organziation
  project: my-project
  authToken: my-token
  release: true
```

https://github.com/arabold/serverless-sentry-plugin/blob/1462dff236a330fc7132457c433ae11a26cc0b3a/src/index.js#L54-L59

https://github.com/arabold/serverless-sentry-plugin/blob/1462dff236a330fc7132457c433ae11a26cc0b3a/src/index.js#L76-L78

Maybe we could use `this._serverless.variables.populateObject()` directly on `custom` instead of `custom.sentry` (and only if sentry is an object) ?
