### ISSUE TITLE
Suport for Serverless V 1.5+

### ISSUE THREAD

**Issue by vanerleo** [arabold/serverless-sentry-plugin#7]
Any chance of getting this to work with the latest serverless?

**Comment by arabold** [comment]
I'd be interested in porting it, but quite frankly we're still relying on the 0.5 branch internally. Therefore I don't have a timeline for this right now.

**Comment by Stubbs** [comment]
Do you have any idea what would be involved in porting it?

**Comment by flux627** [comment]
I'd be interested in helping out with this port as well

**Comment by arabold** [comment]
With the latest improvements and plugins for Serverless 1.9.0 we can finally upgrade our own environment from 0.5. This means I will start working on this plugin again and see how we can port it over to the latest platform. No ETA yet, but I wanted to keep you guys updated. Thanks for your support.

**Comment by Stubbs** [comment]
That's great news Andre.

**Comment by vanerleo** [comment]
Nice

**Comment by arabold** [comment]
The plugin isn't ready yet as I'm still evaluating what's the best way of hooking Sentry into our Lambda Functions handlers. But here's a Gist for a helper file that is already usable: https://gist.github.com/arabold/1e605ce424033a6b63cc6c6d370b1aef

To use this, put the `raven-lambda.js` from the Gist somewhere in your local folder structure and install the latest raven module (`npm install --save raven`). You will further need to add new environment variables to your `serverless.yaml`:
```yaml
service: my-serverless-project
provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-east-1
  environment:
    SERVERLESS_PROJECT: ${self:service}
    SERVERLESS_STAGE: ${opt:stage, self:provider.stage}
    SERVERLESS_REGION: ${opt:region, self:provider.region}
    SENTRY_DSN: https://xxxx:yyyy@sentry.io/zzzz
```

Finally, in your `handler.js` do something like this:
```javascript
const RavenLambdaWrapper = require("./raven-lambda");
const ravenConfig = { /* custom options go here */ };

// Wrap handler for automated error and exception logging
module.exports.handler = RavenLambdaWrapper.handler(ravenConfig, (event, context, callback) => {
  // your Lambda Functions Handler code goes here...
});
```

If any of you has a few minutes and want to give it a shot, let me know your results.
